# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyper_bench_vector <- function(xin, yin, N, n) {
    .Call('_RrichR_hyper_bench_vector', PACKAGE = 'RrichR', xin, yin, N, n)
}

name_table <- function(lh) {
    .Call('_RrichR_name_table', PACKAGE = 'RrichR', lh)
}

rcpp_hello_world <- function() {
    .Call('_RrichR_rcpp_hello_world', PACKAGE = 'RrichR')
}

fast_factor <- function(x) {
    .Call('_RrichR_fast_factor', PACKAGE = 'RrichR', x)
}

sf <- function(x) {
    .Call('_RrichR_sf', PACKAGE = 'RrichR', x)
}

uniq <- function(xa) {
    .Call('_RrichR_uniq', PACKAGE = 'RrichR', xa)
}

