# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyper_bench_vector <- function(xin, yin, N, n) {
    .Call('_RichR_hyper_bench_vector', PACKAGE = 'RichR', xin, yin, N, n)
}

name_table <- function(lh) {
    .Call('_RichR_name_table', PACKAGE = 'RichR', lh)
}

rcpp_hello_world <- function() {
    .Call('_RichR_rcpp_hello_world', PACKAGE = 'RichR')
}

fast_factor <- function(x) {
    .Call('_RichR_fast_factor', PACKAGE = 'RichR', x)
}

sf <- function(x) {
    .Call('_RichR_sf', PACKAGE = 'RichR', x)
}

uniq <- function(xa) {
    .Call('_RichR_uniq', PACKAGE = 'RichR', xa)
}

